# Generated by Django 2.2 on 2021-11-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection_request',
            name='status_of',
            field=models.CharField(choices=[('Request', 'Request'), ('Declined', 'Declined')], default='', max_length=30, null=True),
        ),
    ]
