# Generated by Django 2.2 on 2021-11-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_connection_request_status_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection_request',
            name='status_of',
            field=models.CharField(choices=[('Request', 'Request'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='', max_length=30, null=True),
        ),
    ]
